#!/bin/sh
### BEGIN INIT INFO
# Provides:		debian-devel-changes-bot
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	debian-devel-changes-bot
# Description:		debian-devel-changes-bot - #debian-devel-changes IRC bot
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

NAME=debian-devel-changes-bot
DESC="#debian-devel-changes IRC bot"

USER=ddc-bot
GROUP=${USER}
DAEMON=/usr/bin/supybot
RUNDIR=/var/lib/debian-devel-changes-bot
PIDFILE=/var/run/${NAME}/${NAME}.pid

set -e

if [ ! -d ${RUNDIR} ]
then
	exit 0
fi

case "$1" in
  start)
	echo -n "Starting ${DESC}: "

	if [ "$(id -u)" -ne 0 ]
	then
		echo "failed: must be called as root"
		exit 1
	fi

	mkdir -p $(dirname ${PIDFILE})
	chown ${USER}:${GROUP} $(dirname ${PIDFILE})

	if start-stop-daemon --start --oknodo --quiet --pidfile ${PIDFILE} \
		--chuid ${USER}:${GROUP} --chdir ${RUNDIR} \
		--exec ${DAEMON} -- --daemon bot-config/BTS.conf
	then
		echo "${NAME}."
	else
		echo "failed"
		exit 1
	fi
	;;
  stop)
	echo -n "Stopping ${DESC}: "

	if [ "$(id -u)" -ne 0 ]
	then
		echo "failed: must be called as root"
		exit 1
	fi

	if start-stop-daemon --stop --oknodo --quiet --retry 10 --pidfile ${PIDFILE}
	then
		echo "${NAME}."
		rm -f ${PIDFILE}
	else
		echo "failed"
		exit 1
	fi
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;
  *)
	echo "Usage: /etc/init.d/${NAME} {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
