#!/bin/sh

set -eu

BASE="/var/lib/debian-devel-changes-bot"
USER="ddc-bot"
GROUP="${USER}"

if [ "$1" = "configure" ]
then
  addgroup --system ${GROUP} --quiet

  adduser \
    --system \
    --disabled-login \
    --ingroup ${GROUP} \
    --home ${BASE} \
    --gecos "${USER} server" \
    --shell /bin/false \
    ${USER}  >/dev/null

  ln -sf ${BASE}/bot-config/forward ${BASE}/.forward

  chown -R ${USER}:${GROUP} ${BASE}
fi

#DEBHELPER#

exit 0
