#!/bin/sh

set -eu

USER="ddc-bot"
GROUP="$USER"

ln -sf /var/lib/debian-devel-changes-bot/bot-config/forward /var/lib/debian-devel-changes-bot/.forwar

chown -R $USER:$GROUP /var/lib/debian-devel-changes-bot

#DEBHELPER#
